version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - db